### ISSUE TITLE
react-navigation/src/views/CardStack

### ISSUE THREAD

**Issue by hejun041** [shimohq/shimo-navigation#3]
import CardStack from 'react-navigation/src/views/CardStack/CardStack'
instead
import CardStack from 'react-navigation/src/views/CardStack'
&&
import TransitionConfigs from 'react-navigation/src/views/CardStack/TransitionConfigs';
instead
import TransitionConfigs from 'react-navigation/src/views/TransitionConfigs'
&&
CardStackTransitioner.js
&&
Header.js
the same question

**Comment by tion126** [comment]
好像最近都没人维护了，可以先在postinstall的时候改改吧。
sed -i '' "s/react\-navigation\/src\/views\/CardStack\'/react\-navigation\/src\/views\/CardStack\/CardStack\'/" ./node_modules/shimo-navigation/src/views/CardStack.js

sed -i '' "s/react\-navigation\/src\/views\/TransitionConfigs\'/react\-navigation\/src\/views\/CardStack\/TransitionConfigs\'/" ./node_modules/shimo-navigation/src/views/CardStack.js

sed -i '' "s/react\-navigation\/src\/views\/Header\'/react\-navigation\/src\/views\/Header\/Header\'/" ./node_modules/shimo-navigation/src/views/Header.js

sed -i '' "s/react\-navigation\/src\/views\/HeaderStyleInterpolator\'/react\-navigation\/src\/views\/Header\/HeaderStyleInterpolator\'/" ./node_modules/shimo-navigation/src/views/Header.js

sed -i '' "s/react\-navigation\/src\/views\/CardStackTransitioner\'/react\-navigation\/src\/views\/CardStack\/CardStackTransitioner\'/" ./node_modules/shimo-navigation/src/views/CardStackTransitioner.js

**Comment by magicismight** [comment]
更新最近的版本就可以修复
