### ISSUE TITLE
同一个Screen不能添加多次

### ISSUE THREAD

**Issue by fenglu09** [shimohq/shimo-navigation#4]
同一个页面，跳转的时候，不能多次添加。
例如： listA -> detail -> listB -> detail
从listB就无法跳转到detail
最新版的`react-navigtion` 可以跳转.

请问这库还在维护吗？还会更新吗？

**Comment by magicismight** [comment]
参考 https://github.com/shimohq/shimo-navigation/blob/master/Example/components/Folder.js
给组件指定一个静态方法 `static screenKey = (routeName, params) => `${routeName}/${params.guid}`;` 
结合参数生成一个唯一的 key，这样做是为了防止重复推入相同的界面，保证每个界面都是唯一的
还在维护，在修复bug或者我们需要添加功能的时候都会及时更新

**Comment by magicismight** [comment]
公司项目自用代码，没花太多心思写文档，修改和加的内容可以在源代码或者例子里面找

**Comment by fenglu09** [comment]
好的，期待ing
